language: objective-c
osx_image: xcode7.2
xcode_project: Examples/CrutchKitExample/CrutchKitExample.xcworkspace
xcode_scheme: CrutchKitExample
script: xctool test -workspace Examples/CrutchKitExample/CrutchKitExample.xcworkspace -scheme CrutchKitExample -sdk iphonesimulator9.2
